### ISSUE TITLE
Where are the Events?

### ISSUE THREAD

**Issue by Hodel1** [lucavinci/bungeeban#7]
Hi,
your Wiki includes introductions for developers.
But the Events are not included in the Jar or Javadocs.

https://lucavinci.github.io/javadocs/bungeeban/

Now, how can i detect the Events?

**Comment by lucavinci** [comment]
I updated the javadoc at https://lucavinci.github.io/javadocs/bungeeban/ .
The events are located in ´de.lucavinci.bungeeban.events´. Thanks for making me aware.

Is your question answered now or do you have further questions?

**Comment by Hodel1** [comment]
No thanks, you can close this thread :)

**Comment by lucavinci** [comment]
Ok. Thanks :)
